# Generated by Django 2.2.1 on 2019-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190526_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_png_RlEXbqA.png', null=True, upload_to='images/'),
        ),
    ]
