# Generated by Django 2.2.1 on 2019-05-16 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_auto_20190516_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lessons',
        ),
    ]
