# Generated by Django 2.2.1 on 2019-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_auto_20190517_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='grade',
            field=models.BooleanField(default=False),
        ),
    ]
