# Generated by Django 2.2.1 on 2019-05-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_auto_20190517_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='video_file',
            new_name='lesson_file',
        ),
    ]
