# Generated by Django 2.2.1 on 2019-05-18 12:04

from django.db import migrations, models
import lesson.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_auto_20190517_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
