# Generated by Django 2.2.1 on 2019-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_auto_20190518_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
