# Generated by Django 2.2.1 on 2019-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_auto_20190519_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
