# Generated by Django 2.2.1 on 2019-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_auto_20190519_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
