# Generated by Django 2.2.1 on 2019-05-22 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0017_auto_20190522_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
        migrations.AddField(
            model_name='lessons',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='lesson.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lesson.Lessons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
