# Generated by Django 2.2.1 on 2019-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0019_auto_20190522_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
