# Generated by Django 2.2.1 on 2019-05-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0022_auto_20190522_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
