# Generated by Django 2.2.1 on 2019-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0024_auto_20190523_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='lesson_file',
        ),
        migrations.AddField(
            model_name='lessons',
            name='content',
            field=models.TextField(default=models.CharField(max_length=50), max_length=400),
        ),
    ]
