# Generated by Django 2.2.1 on 2019-05-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0025_auto_20190523_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='content',
            field=models.TextField(default='No content', max_length=400),
        ),
    ]
