# Generated by Django 2.2.1 on 2019-05-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='creator',
            new_name='to_creator',
        ),
    ]
