# Generated by Django 2.2.1 on 2019-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_auto_20190521_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='title',
            field=models.CharField(default='NoTittle', max_length=255),
        ),
    ]
